# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(222123)
$foreground = rgb(EBCFB7)
$color0 = rgb(48474A)
$color1 = rgb(1C1720)
$color2 = rgb(231B20)
$color3 = rgb(433228)
$color4 = rgb(513422)
$color5 = rgb(855124)
$color6 = rgb(945924)
$color7 = rgb(DAB38F)
$color8 = rgb(997D64)
$color9 = rgb(251F2B)
$color10 = rgb(2F242B)
$color11 = rgb(594336)
$color12 = rgb(6B452D)
$color13 = rgb(B26C2F)
$color14 = rgb(C67730)
$color15 = rgb(DAB38F)
