# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111212)
$foreground = rgb(F1F0EE)
$color0 = rgb(393A3A)
$color1 = rgb(0A0E0E)
$color2 = rgb(542C1C)
$color3 = rgb(2D3B3D)
$color4 = rgb(9D4416)
$color5 = rgb(AC7C55)
$color6 = rgb(A19E9B)
$color7 = rgb(E3E1DF)
$color8 = rgb(9F9D9C)
$color9 = rgb(0D1313)
$color10 = rgb(703B26)
$color11 = rgb(3C4E51)
$color12 = rgb(D15A1D)
$color13 = rgb(E5A571)
$color14 = rgb(D7D3CF)
$color15 = rgb(E3E1DF)
