# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1B1C1E)
$foreground = rgb(C7F0ED)
$color0 = rgb(414345)
$color1 = rgb(0F161D)
$color2 = rgb(0F161D)
$color3 = rgb(582072)
$color4 = rgb(07446E)
$color5 = rgb(255B5C)
$color6 = rgb(47A099)
$color7 = rgb(A7E2DD)
$color8 = rgb(759E9B)
$color9 = rgb(141D27)
$color10 = rgb(141D27)
$color11 = rgb(762B98)
$color12 = rgb(095B93)
$color13 = rgb(31797A)
$color14 = rgb(5FD5CC)
$color15 = rgb(A7E2DD)
