#!/bin/bash

# Configuration
USER_NAME="hit235"
USER_ID=$(id -u $USER_NAME)
MONITOR="eDP-1"

# Find Hyprland signature
export HYPRLAND_INSTANCE_SIGNATURE=$(ls -t /run/user/$USER_ID/hypr | head -n 1)
export XDG_RUNTIME_DIR="/run/user/$USER_ID"

# Get DBUS address for notifications
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$USER_ID/bus"

# Check AC Status
AC_STATUS=$(cat /sys/class/power_supply/AC0/online)

# Default fallback values in case monitors.conf is not found or empty
RES="highres"
POS="auto"
SCALE="1.2"
OPTIONS="bitdepth,10"

# Parse user preferred layout from monitors.conf (generated by display settings app)
if [ -f "/home/$USER_NAME/.config/hypr/monitors.conf" ]; then
    MONITOR_LINE=$(grep "^monitor\s*=\s*$MONITOR" "/home/$USER_NAME/.config/hypr/monitors.conf" || grep "^monitor\s*=\s*," "/home/$USER_NAME/.config/hypr/monitors.conf" || echo "")
    if [ -n "$MONITOR_LINE" ]; then
        clean_line=$(echo "$MONITOR_LINE" | sed 's/^monitor\s*=\s*//')
        IFS=',' read -r -a parts <<< "$clean_line"
        if [ ${#parts[@]} -ge 4 ]; then
            RES="${parts[1]}"
            POS="${parts[2]}"
            SCALE="${parts[3]}"
            OPTIONS=""
            for ((i=4; i<${#parts[@]}; i++)); do
                if [ -n "$OPTIONS" ]; then
                    OPTIONS="$OPTIONS,${parts[i]}"
                else
                    OPTIONS="${parts[i]}"
                fi
            done
        fi
    fi
fi

# Strip any existing refresh rate from resolution to set it dynamically
base_res=$(echo "$RES" | sed 's/@.*//')

# Function to run command with drop permissions if root, or directly if user
run_cmd() {
    if [ "$(id -u)" -eq 0 ]; then
        sudo -u $USER_NAME -E "$@"
    else
        "$@"
    fi
}

if [ "$AC_STATUS" -eq 1 ]; then
    # PLUGGED IN: Go to 120Hz (keep user's resolution, position, scale, and options)
    if [ -n "$OPTIONS" ]; then
        monitor_cmd="$MONITOR,$base_res@120.0,$POS,$SCALE,$OPTIONS"
    else
        monitor_cmd="$MONITOR,$base_res@120.0,$POS,$SCALE"
    fi
    run_cmd hyprctl keyword monitor "$monitor_cmd"
    run_cmd notify-send -t 2000 -i "power-plug" "Power Connected" "Switching to 120Hz" || true
else
    # ON BATTERY: Drop to 60Hz (keep user's resolution, position, scale, and options)
    if [ -n "$OPTIONS" ]; then
        monitor_cmd="$MONITOR,$base_res@60,$POS,$SCALE,$OPTIONS"
    else
        monitor_cmd="$MONITOR,$base_res@60,$POS,$SCALE"
    fi
    run_cmd hyprctl keyword monitor "$monitor_cmd"
    run_cmd notify-send -t 2000 -i "battery-low" "Power Disconnected" "Switching to 60Hz to save battery" || true
fi
