# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Launch Waybar
# exec-once = waybar &

# Launch Mac-style Dock
exec-once = ~/.config/hypr/scripts/RefreshRate.sh &
