# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Launch Waybar
# exec-once = waybar &

# Launch Mac-style Dock & Power Monitor (managed by systemd user service)
# exec-once = ~/.config/hypr/scripts/PowerMonitor.sh &

# Launch nwg-dock-hyprland macOS style left dock
exec-once = nwg-dock-hyprland -d -p left -i 48 -ml 6 -nolauncher &
