# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Launch Waybar
# exec-once = waybar &

# Launch Mac-style Dock & Power Monitor (managed by systemd user service)
# exec-once = ~/.config/hypr/scripts/PowerMonitor.sh &
