# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this

exec-once = hyprctl setcursor Bibata-Modern-Ice 24
# exec-once = hyprctl setcursor Bibata-Modern-Classic 24

input {
  sensitivity = 0.5
}

device {
  name = logi-m196-mouse
  sensitivity = 0.8
}

