# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

layerrule = match:namespace nwg-dock, blur on
layerrule = match:namespace nwg-dock, ignore_alpha 0.01

# Custom Window Opacities (Option 1: Decreasing blur on non-active apps by making them more solid)
windowrule = match:tag terminal, opacity 0.9 0.85
windowrule = match:tag projects, opacity 0.9 0.9
windowrule = match:class ^(code-oss|code|Code|code-insiders)$, opacity 0.9 0.9

# Rules for snmenu (circular power menu) to float as a transparent overlay
windowrule {
    name = snmenu-overlay
    match:class = ^(snmenu)$
    float = on
    size = (monitor_w) (monitor_h)
    move = 0 0
    pin = on
}
