-- Generated by nwg-displays on 2026-06-06 at 23:41:35. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "0x0",
    scale = 1.6,
    bitdepth = 10
})
