-- Generated by nwg-displays on 2026-06-29 at 10:27:40. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "0x0",
    scale = 1.5,
    bitdepth = 10
})
