-- Generated by nwg-displays on 2026-07-18 at 05:44:42. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "2590x120",
    scale = 1.0
})
