# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FBABF3
background         #1A1520
cursor             #8B59A1

active_tab_foreground     #1A1520
active_tab_background     #FBABF3
inactive_tab_foreground   #FBABF3
inactive_tab_background   #1A1520

active_border_color   #FBABF3
inactive_border_color #1A1520
bell_border_color     #140635

color0      #413C49
color1		#140635
color2		#15063C
color3		#1A0643
color4		#55059B
color5		#6405B1
color6		#B60BA6
color7		#F17EE6
color8		#A858A1
color9		#1A0847
color10		#1C0850
color11		#230859
color12		#7106CF
color13		#8506EC
color14		#F30EDD
color15		#F17EE6
