# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F2E6C5
background         #191412
cursor             #B49069

active_tab_foreground     #191412
active_tab_background     #F2E6C5
inactive_tab_foreground   #F2E6C5
inactive_tab_background   #191412

active_border_color   #F2E6C5
inactive_border_color #191412
bell_border_color     #261207

color0      #413B3A
color1		#261207
color2		#592B0A
color3		#4F3A1B
color4		#7D3F0F
color5		#79622F
color6		#A38943
color7		#E4D3A4
color8		#9F9372
color9		#321909
color10		#773A0E
color11		#6A4D24
color12		#A75414
color13		#A1823E
color14		#D9B759
color15		#E4D3A4
