# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #BFE5F8
background         #221B29
cursor             #A586AF

active_tab_foreground     #221B29
active_tab_background     #BFE5F8
inactive_tab_foreground   #BFE5F8
inactive_tab_background   #221B29

active_border_color   #BFE5F8
inactive_border_color #221B29
bell_border_color     #230B43

color0      #494251
color1		#230B43
color2		#681D4D
color3		#6D166B
color4		#A42E55
color5		#A42E55
color6		#3688B0
color7		#9BD2ED
color8		#6D93A6
color9		#2E0E5A
color10		#8B2766
color11		#921D8F
color12		#DB3D71
color13		#DB3D71
color14		#48B6EB
color15		#9BD2ED
